server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.10.227.132:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 10.10.227.132
    virtual-host: /leyou
    username: leyou
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15


